from __future__ import annotations

import re
import unicodedata
from typing import TypedDict


class UniversityCatalogItem(TypedDict, total=False):
    name: str
    city: str | None
    faculties: list[str]
    aliases: list[str]


def _normalize_university_key(value: str) -> str:
    # Normalize casing + diacritics + punctuation/whitespace so we can match legacy inputs.
    value = value.strip().casefold()
    value = (
        value.replace("“", '"')
        .replace("”", '"')
        .replace("’", "'")
        .replace("–", "-")
        .replace("—", "-")
    )
    value = unicodedata.normalize("NFKD", value)
    value = "".join(ch for ch in value if not unicodedata.combining(ch))
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return " ".join(value.split())


def _guess_city(name: str) -> str | None:
    lowered = name.lower()
    mapping = [
        ("romanian-american", "București"),
        ("spiru haret", "București"),
        ("bucharest", "București"),
        ("bucuresti", "București"),
        ("cluj-napoca", "Cluj-Napoca"),
        ("cluj", "Cluj-Napoca"),
        ("iasi", "Iași"),
        ("timisoara", "Timișoara"),
        ("targu mures", "Târgu Mureș"),
        ("targu-mures", "Târgu Mureș"),
        ("sibiu", "Sibiu"),
        ("constanta", "Constanța"),
        ("craiova", "Craiova"),
        ("galatzi", "Galați"),
        ("brasov", "Brașov"),
        ("oradea", "Oradea"),
        ("emanuel", "Oradea"),
        ("suceava", "Suceava"),
        ("petrosani", "Petroșani"),
        ("pitesti", "Pitești"),
        ("arad", "Arad"),
        ("ploiesti", "Ploiești"),
        ("targu jiu", "Târgu Jiu"),
        ("targoviste", "Târgoviște"),
        ("alba iulia", "Alba Iulia"),
        ("baia mare", "Baia Mare"),
        ("resita", "Reșița"),
        ("bacau", "Bacău"),
    ]
    for needle, city in mapping:
        if needle in lowered:
            return city
    return None


# Note: Faculty lists are curated and incomplete; if a university is missing from this map, the UI
# falls back to manual input for the faculty field.
_FACULTIES_BY_UNIVERSITY: dict[str, list[str]] = {
    "1 December University of Alba Iulia": [
        "Facultatea de Istorie, Litere și Științe ale Educației",
        "Facultatea de Drept și Științe Sociale",
        "Facultatea de Informatică și Inginerie",
        "Facultatea de Științe Economice",
        "Facultatea de Teologie Ortodoxă",
    ],
    "Academia Tehnica Militara": [
        "Facultatea de Comunicații și Sisteme Electronice pentru Apărare și Securitate",
        "Facultatea de Sisteme Informatice și Securitate Cibernetică",
        "Facultatea de Sisteme Integrate de Armament, Geniu și Mecatronică",
        "Facultatea de Aeronave și Autovehicule Militare",
    ],
    "Academia de Studii Economice din Bucuresti": [
        "Facultatea de Administrarea Afacerilor cu predare în limbi străine",
        "Facultatea de Administrație și Management Public",
        "Facultatea de Business și Turism",
        "Facultatea de Cibernetică, Statistică și Informatică Economică",
        "Facultatea de Contabilitate și Informatică de Gestiune",
        "Facultatea de Drept",
        "Facultatea de Economie Agroalimentară și a Mediului",
        "Facultatea de Economie Teoretică și Aplicată",
        "Facultatea de Finanțe, Asigurări, Bănci și Burse de Valori",
        "Facultatea de Management",
        "Facultatea de Marketing",
        "Facultatea de Relații Economice Internaționale",
    ],
    "Academy of Arts \"George Enescu\" Iasi": [
        "Facultatea de Interpretare, Compoziție și Studii Muzicale Teoretice",
        "Facultatea de Teatru",
        "Facultatea de Arte Vizuale și Design",
    ],
    "Academy of Music \"Georghe Dima\" Cluj-Napoca": [
        "Facultatea de Interpretare Muzicală",
        "Facultatea Teoretică",
    ],
    "Babes-Bolyai University of Cluj-Napoca": [
        "Facultatea de Matematică și Informatică",
        "Facultatea de Fizică",
        "Facultatea de Chimie și Inginerie Chimică",
        "Facultatea de Biologie și Geologie",
        "Facultatea de Business",
        "Facultatea de Geografie",
        "Facultatea de Știința și Ingineria Mediului",
        "Facultatea de Drept",
        "Facultatea de Litere",
        "Facultatea de Istorie și Filosofie",
        "Facultatea de Sociologie și Asistență Socială",
        "Facultatea de Psihologie și Științe ale Educației",
        "Facultatea de Științe Economice și Gestiunea Afacerilor",
        "Facultatea de Studii Europene",
        "Facultatea de Științe Politice, Administrative și ale Comunicării",
        "Facultatea de Educație Fizică și Sport",
        "Facultatea de Teologie Ortodoxă",
        "Facultatea de Teologie Greco-Catolică",
        "Facultatea de Teologie Reformată",
        "Facultatea de Teologie Romano-Catolică",
        "Facultatea de Teatru și Televiziune",
        "Facultatea de Inginerie",
    ],
    "Constantin Brancoveanu University Pitesti": [
        "Facultatea de Management Marketing în Afaceri Economice",
        "Facultatea de Finanțe Contabilitate",
        "Facultatea de Științe Juridice, Administrative și ale Comunicării",
    ],
    "Emanuel University": [
        "Facultatea de Teologie",
        "Facultatea de Management",
    ],
    "Institute of Architecture \"Ion Mincu\" Bucharest": [
        "Facultatea de Arhitectură",
        "Facultatea de Urbanism",
        "Facultatea de Arhitectură de Interior",
    ],
    "Maritime University Constanta": [
        "Facultatea de Navigație și Transport Naval",
        "Facultatea de Electromecanică Navală",
    ],
    "National Academy for Physical Education and Sports Bucharest": [
        "Facultatea de Educație Fizică și Sport",
        "Facultatea de Kinetoterapie",
    ],
    "National School of Political and Administrative Studies Bucharest": [
        "Facultatea de Administrație Publică",
        "Facultatea de Comunicare și Relații Publice",
        "Facultatea de Management",
        "Facultatea de Științe Politice",
    ],
    "National University of Arts": [
        "Facultatea de Arte Plastice",
        "Facultatea de Arte Decorative și Design",
        "Facultatea de Istoria și Teoria Artei",
    ],
    "National University of Music": [
        "Facultatea de Compoziție, Muzicologie și Pedagogie muzicală",
        "Facultatea de Interpretare Muzicală",
    ],
    "National University of Theater and Film Arts": [
        "Facultatea de Teatru",
        "Facultatea de Film",
    ],
    "North University of Baia Mare": [
        "Facultatea de Inginerie",
        "Facultatea de Litere",
        "Facultatea de Științe",
    ],
    "Oradea University": [
        "Facultatea de Arte",
        "Facultatea de Construcții, Cadastru și Arhitectură",
        "Facultatea de Drept",
        "Facultatea de Geografie, Turism și Sport",
        "Facultatea de Inginerie Electrică și Tehnologia Informației",
        "Facultatea de Inginerie Energetică și Management Industrial",
        "Facultatea de Inginerie Managerială și Tehnologică",
        "Facultatea de Istorie, Relații Internaționale, Științe Politice și Științele Comunicării",
        "Facultatea de Litere",
        "Facultatea de Medicină și Farmacie",
        "Facultatea de Protecția Mediului",
        "Facultatea de Informatică și Științe",
        "Facultatea de Științe Economice",
        "Facultatea de Științe Socio-Umane",
        "Facultatea de Teologie Ortodoxă „Episcop Dr. Vasile Coman”",
    ],
    "Petru Maior University of Targu Mures": [
        "Facultatea de Inginerie",
        "Facultatea de Științe și Litere",
        "Facultatea de Științe Economice, Juridice și Administrative",
    ],
    "Polytechnic University of Timisoara": [
        "Facultatea de Arhitectură și Urbanism",
        "Facultatea de Automatică și Calculatoare",
        "Facultatea de Chimie Industrială și Ingineria Mediului",
        "Facultatea de Construcții",
        "Facultatea de Hidrotehnică",
        "Facultatea de Electronică, Telecomunicații și Tehnologii Informaționale",
        "Facultatea de Inginerie Electrică și Energetică",
        "Facultatea de Management în Producție și Transporturi",
        "Facultatea de Mecanică",
        "Facultatea de Inginerie din Hunedoara",
        "Facultatea de Științe ale Comunicării",
    ],
    "Romanian-American University": [
        "Facultatea de Afaceri Internaționale",
        "Facultatea de Drept",
        "Facultatea de Educație Fizică, Sport și Kinetoterapie",
        "Facultatea de Finanțe și Contabilitate",
        "Facultatea de Informatică Managerială",
        "Facultatea de Management-Marketing",
        "Facultatea de Psihologie și Științele Educației",
        "Facultatea de Turism și Managementul Ospitalității",
    ],
    "Spiru Haret University": [
        "Facultatea de Arhitectură (București)",
        "Facultatea de Arte (București)",
        "Facultatea de Științe Juridice și Administrative (Brașov)",
        "Facultatea de Științe Juridice, Politice și Administrative (București)",
        "Facultatea de Contabilitate și Finanțe (Râmnicu Vâlcea)",
        "Facultatea de Drept și Administrație Publică (Constanța)",
        "Facultatea de Drept și Administrație Publică (Craiova)",
        "Facultatea de Drept și Administrație Publică (Râmnicu Vâlcea)",
        "Facultatea de Științe Economice (Câmpulung-Muscel)",
        "Facultatea de Educație Fizică și Sport (București)",
        "Facultatea de Psihologie și Științele Educației (București)",
        "Facultatea de Finanțe și Bănci (București)",
        "Facultatea de Jurnalism și Științele Comunicării (București)",
        "Facultatea de Litere (București)",
        "Facultatea de Management (Brașov)",
        "Facultatea de Management Financiar Contabil (București)",
        "Facultatea de Management Financiar Contabil (Craiova)",
        "Facultatea de Management Financiar Contabil (Constanța)",
        "Facultatea de Marketing și Afaceri Economice Internaționale (București)",
        "Facultatea de Matematică, Informatică și Științele Naturii (București)",
        "Facultatea de Medicină Veterinară (București)",
        "Facultatea de Psihologie și Pedagogie (Brașov)",
        "Facultatea de Relații Internaționale, Istorie și Filosofie (București)",
    ],
    "Targu-Mures University of Theatre": [
        "Facultatea de Arte în Limba Română",
    ],
    "Technical University of Civil Engineering Bucharest": [
        "Facultatea de Construcții Civile, Industriale și Agricole",
        "Facultatea de Inginerie a Instalațiilor",
        "Facultatea de Hidrotehnică",
        "Facultatea de Căi Ferate, Drumuri și Poduri",
        "Facultatea de Geodezie",
        "Facultatea de Inginerie în Limbi Străine",
        "Facultatea de Utilaj Tehnologic",
    ],
    "Technical University of Cluj-Napoca": [
        "Facultatea de Automatică și Calculatoare",
        "Facultatea de Electronică, Telecomunicații și Tehnologia Informației",
        "Facultatea de Inginerie Electrică",
        "Facultatea de Construcții",
        "Facultatea de Instalații",
        "Facultatea de Construcții de Mașini",
        "Facultatea de Inginerie Industrială, Robotică și Managementul Producției",
        "Facultatea de Mecanică",
        "Facultatea de Autovehicule Rutiere, Mecatronică și Mecanică",
        "Facultatea de Știința și Ingineria Materialelor",
        "Facultatea de Ingineria Materialelor și a Mediului",
        "Facultatea de Arhitectură și Urbanism",
        "Facultatea de Inginerie",
        "Facultatea de Litere",
        "Facultatea de Științe",
    ],
    "Technical University of Iasi": [
        "Facultatea de Arhitectură „G. M. Cantacuzino”",
        "Facultatea de Automatică și Calculatoare",
        "Facultatea de Construcții și Instalații",
        "Facultatea de Construcții de Mașini și Management Industrial",
        "Facultatea de Design Industrial și Managementul Afacerilor",
        "Facultatea de Electronică, Telecomunicații și Tehnologia Informației",
        "Facultatea de Hidrotehnică, Geodezie și Ingineria Mediului",
        "Facultatea de Inginerie Chimică și Protecția Mediului „Cristofor Simionescu”",
        "Facultatea de Inginerie Electrică, Energetică și Informatică Aplicată",
        "Facultatea de Mecanică",
        "Facultatea de Știința și Ingineria Materialelor",
    ],
    "Technical University of Timisoara": [
        "Facultatea de Arhitectură și Urbanism",
        "Facultatea de Automatică și Calculatoare",
        "Facultatea de Chimie Industrială și Ingineria Mediului",
        "Facultatea de Construcții",
        "Facultatea de Hidrotehnică",
        "Facultatea de Electronică, Telecomunicații și Tehnologii Informaționale",
        "Facultatea de Inginerie Electrică și Energetică",
        "Facultatea de Management în Producție și Transporturi",
        "Facultatea de Mecanică",
        "Facultatea de Inginerie din Hunedoara",
        "Facultatea de Științe ale Comunicării",
    ],
    "Universitatea de Vest \"Vasile Goldiş\"": [
        "Facultatea de Medicină",
        "Facultatea de Farmacie",
        "Facultatea de Medicină Dentară",
        "Facultatea de Științe Economice, Inginerie și Informatică",
        "Facultatea de Științe Juridice",
        "Facultatea de Științe Socio-Umane, Educației Fizice și Sport",
    ],
    "University \"Aurel Vlaicu\" Arad": [
        "Facultatea de Științe Economice",
        "Facultatea de Științe Exacte",
        "Facultatea de Științe Umaniste și Sociale",
        "Facultatea de Științe ale Educației, Psihologie și Asistență Socială",
        "Facultatea de Teologie Ortodoxă „Ilarion V. Felea”",
        "Facultatea de Inginerie",
        "Facultatea de Inginerie Alimentară, Turism și Protecția Mediului",
        "Facultatea de Educație Fizică și Sport",
        "Facultatea de Design",
    ],
    "University \"Petre Andrei\" Iasi": [
        "Facultatea de Psihologie și Științele Educației",
        "Facultatea de Asistență Socială și Sociologie",
        "Facultatea de Științe Politice și Administrative",
        "Facultatea de Drept",
        "Facultatea de Economie",
    ],
    "University \"Titu Maiorescu\"": [
        "Facultatea de Drept",
        "Facultatea de Psihologie",
        "Facultatea de Informatică",
        "Facultatea de Științe Economice",
        "Facultatea de Medicină",
        "Facultatea de Medicină Dentară",
        "Facultatea de Farmacie",
        "Facultatea de Științele Educației, Comunicare și Relații Internaționale",
        "Facultatea de Asistență Medicală",
    ],
    "University \"Transilvania\" of Brasov": [
        "Facultatea de Inginerie Tehnologică și Management Industrial",
        "Facultatea de Știința și Ingineria Materialelor",
        "Facultatea de Design de Produs și Mediu",
        "Facultatea de Inginerie Electrică și Știința Calculatoarelor",
        "Facultatea de Silvicultură și Exploatări Forestiere",
        "Facultatea de Ingineria Lemnului",
        "Facultatea de Construcții",
        "Facultatea de Științe Economice și Administrarea Afacerilor",
        "Facultatea de Alimentație și Turism",
        "Facultatea de Matematică și Informatică",
        "Facultatea de Muzică",
        "Facultatea de Medicină",
        "Facultatea de Drept",
        "Facultatea de Sociologie și Comunicare",
        "Facultatea de Educație Fizică și Sporturi Montane",
        "Facultatea de Litere",
        "Facultatea de Psihologie și Științele Educației",
    ],
    "University Lucian Blaga of Sibiu": [
        "Facultatea de Teologie",
        "Facultatea de Drept „Simion Bărnuțiu”",
        "Facultatea de Litere și Arte",
        "Facultatea de Științe Socio-Umane",
        "Facultatea de Inginerie",
        "Facultatea de Medicină",
        "Facultatea de Științe",
        "Facultatea de Științe Agricole, Industrie Alimentară și Protecția Mediului",
        "Facultatea de Științe Economice",
    ],
    "University Oil-Gas Ploiesti": [
        "Facultatea de Inginerie Mecanică și Electrică",
        "Facultatea de Ingineria Petrolului și Gazelor",
        "Facultatea de Tehnologia Petrolului și Petrochimie",
        "Facultatea de Litere și Științe",
        "Facultatea de Științe Economice",
    ],
    "University Politehnica of Bucharest": [
        "Facultatea de Automatică și Calculatoare",
        "Facultatea de Antreprenoriat, Ingineria și Managementul Afacerilor",
        "Facultatea de Chimie Aplicată și Știința Materialelor",
        "Facultatea de Energetică",
        "Facultatea de Electronică, Telecomunicații și Tehnologia Informației",
        "Facultatea de Ingineria și Managementul Sistemelor Tehnologice",
        "Facultatea de Ingineria Sistemelor Biotehnice",
        "Facultatea de Inginerie Aerospațială",
        "Facultatea de Inginerie Electrică",
        "Facultatea de Inginerie Medicală",
        "Facultatea de Inginerie Mecanică și Mecatronică",
        "Facultatea de Inginerie cu predare în limbi străine",
        "Facultatea de Transporturi",
        "Facultatea de Știința și Ingineria Materialelor",
        "Facultatea de Științe Aplicate",
    ],
    "University of Agriculture and Veterinary Medicine Bucharest": [
        "Facultatea de Agricultură",
        "Facultatea de Horticultură",
        "Facultatea de Ingineria și Gestiunea Producțiilor Animaliere",
        "Facultatea de Medicină Veterinară",
        "Facultatea de Biotehnologii",
        "Facultatea de Îmbunătățiri Funciare și Ingineria Mediului",
        "Facultatea de Management și Dezvoltare Rurală",
    ],
    "University of Agriculture and Veterinary Medicine Cluj-Napoca": [
        "Facultatea de Agricultură",
        "Facultatea de Horticultură",
        "Facultatea de Zootehnie și Biotehnologii",
        "Facultatea de Medicină Veterinară",
        "Facultatea de Știința și Tehnologia Alimentelor",
        "Facultatea de Silvicultură și Cadastru",
    ],
    "University of Agriculture and Veterinary Medicine Iasi": [
        "Facultatea de Agricultură",
        "Facultatea de Horticultură",
        "Facultatea de Ingineria Resurselor Animale și Alimentare",
        "Facultatea de Medicină Veterinară",
    ],
    "University of Agriculture and Veterinary Medicine Timisoara": [
        "Facultatea de Agricultură",
        "Facultatea de Bioingineria Resurselor Animaliere",
        "Facultatea de Inginerie Alimentară",
        "Facultatea de Inginerie și Tehnologii Aplicate",
        "Facultatea de Management și Turism Rural",
        "Facultatea de Medicină Veterinară",
    ],
    "University of Art and Design Cluj-Napoca": [
        "Facultatea de Arte Plastice",
        "Facultatea de Arte Decorative și Design",
    ],
    "University of Bacau": [
        "Facultatea de Științe",
        "Facultatea de Inginerie",
        "Facultatea de Științe Economice",
        "Facultatea de Litere",
        "Facultatea de Științe ale Mișcării, Sportului și Sănătății",
    ],
    "University of Bucharest": [
        "Facultatea de Administrație și Afaceri",
        "Facultatea de Biologie",
        "Facultatea de Chimie",
        "Facultatea de Drept",
        "Facultatea de Filosofie",
        "Facultatea de Fizică",
        "Facultatea de Geografie",
        "Facultatea de Geologie și Geofizică",
        "Facultatea de Istorie",
        "Facultatea de Jurnalism și Științele Comunicării",
        "Facultatea de Limbi și Literaturi Străine",
        "Facultatea de Litere",
        "Facultatea de Matematică și Informatică",
        "Facultatea de Psihologie și Științele Educației",
        "Facultatea de Sociologie și Asistență Socială",
        "Facultatea de Studii Interdisciplinare",
        "Facultatea de Științe Politice",
        "Facultatea de Teologie Baptistă",
        "Facultatea de Teologie Ortodoxă",
        "Facultatea de Teologie Romano-Catolică și Asistență Socială",
    ],
    "University of Constanta": [
        "Facultatea de Istorie și Științe Politice",
        "Facultatea de Farmacie",
        "Facultatea de Medicină",
        "Facultatea de Psihologie și Științele Educației",
        "Facultatea de Litere",
        "Facultatea de Educație Fizică și Sport",
        "Facultatea de Teologie",
        "Facultatea de Matematică și Informatică",
        "Facultatea de Științe Aplicate și Inginerie",
        "Facultatea de Arte",
        "Facultatea de Științe ale Naturii și Științe Agricole",
        "Facultatea de Drept și Științe Administrative",
        "Facultatea de Construcții",
        "Facultatea de Inginerie Mecanică, Industrială și Maritimă",
    ],
    "University of Constanta Medical School": [
        "Facultatea de Farmacie",
        "Facultatea de Medicină",
    ],
    "University of Craiova": [
        "Facultatea de Agronomie",
        "Facultatea de Automatică, Calculatoare și Electronică",
        "Facultatea de Drept",
        "Facultatea de Economie și Administrarea Afacerilor",
        "Facultatea de Educație Fizică și Sport",
        "Facultatea de Horticultură",
        "Facultatea de Inginerie Electrică",
        "Facultatea de Litere",
        "Facultatea de Mecanică",
        "Facultatea de Teologie Ortodoxă",
        "Facultatea de Științe",
        "Facultatea de Științe Sociale",
    ],
    "University of Galatzi": [
        "Facultatea de Inginerie",
        "Facultatea de Arhitectură Navală",
        "Facultatea de Știința și Ingineria Alimentelor",
        "Facultatea de Automatică, Calculatoare, Inginerie Electrică și Electronică",
        "Facultatea de Educație Fizică și Sport",
        "Facultatea de Litere",
        "Facultatea de Științe și Mediu",
        "Facultatea de Istorie, Filosofie și Teologie",
        "Facultatea de Inginerie și Agronomie din Brăila",
        "Facultatea de Economie și Administrarea Afacerilor",
        "Facultatea de Drept și Științe Administrative",
        "Facultatea de Medicină și Farmacie",
        "Facultatea de Arte",
        "Facultatea Transfrontalieră",
    ],
    "University of Iasi": [
        "Facultatea de Biologie",
        "Facultatea de Chimie",
        "Facultatea de Drept",
        "Facultatea de Economie și Administrarea Afacerilor",
        "Facultatea de Educație Fizică și Sport",
        "Facultatea de Filosofie și Științe Social-Politice",
        "Facultatea de Fizică",
        "Facultatea de Geografie și Geologie",
        "Facultatea de Informatică",
        "Facultatea de Istorie",
        "Facultatea de Litere",
        "Facultatea de Matematică",
        "Facultatea de Psihologie și Științe ale Educației",
        "Facultatea de Teologie Ortodoxă",
        "Facultatea de Teologie Romano-Catolică",
    ],
    "University of Medicine and Pharmacology of Oradea": [
        "Facultatea de Medicină și Farmacie",
    ],
    "University of Medicine and Pharmacy of Bucharest": [
        "Facultatea de Medicină",
        "Facultatea de Medicină Dentară",
        "Facultatea de Farmacie",
        "Facultatea de Moașe și Asistență Medicală",
    ],
    "University of Medicine and Pharmacy of Cluj-Napoca": [
        "Facultatea de Medicină",
        "Facultatea de Medicină Dentară",
        "Facultatea de Farmacie",
    ],
    "University of Medicine and Pharmacy of Iasi": [
        "Facultatea de Medicină",
        "Facultatea de Medicină Dentară",
        "Facultatea de Farmacie",
        "Facultatea de Bioinginerie Medicală",
    ],
    "University of Medicine and Pharmacy of Targu Mures": [
        "Facultatea de Medicină",
        "Facultatea de Medicină Dentară",
        "Facultatea de Medicină Engleză",
        "Facultatea de Farmacie",
        "Facultatea de Inginerie și Tehnologia Informației",
        "Facultatea de Științe și Litere",
        "Facultatea de Economie și Drept",
    ],
    "University of Medicine and Pharmacy of Timisoara": [
        "Facultatea de Medicină",
        "Facultatea de Medicină Dentară",
        "Facultatea de Farmacie",
    ],
    "University of Oradea": [
        "Facultatea de Arte",
        "Facultatea de Construcții, Cadastru și Arhitectură",
        "Facultatea de Drept",
        "Facultatea de Geografie, Turism și Sport",
        "Facultatea de Inginerie Electrică și Tehnologia Informației",
        "Facultatea de Inginerie Energetică și Management Industrial",
        "Facultatea de Inginerie Managerială și Tehnologică",
        "Facultatea de Istorie, Relații Internaționale, Științe Politice și Științele Comunicării",
        "Facultatea de Litere",
        "Facultatea de Medicină și Farmacie",
        "Facultatea de Protecția Mediului",
        "Facultatea de Informatică și Științe",
        "Facultatea de Științe Economice",
        "Facultatea de Științe Socio-Umane",
        "Facultatea de Teologie Ortodoxă „Episcop Dr. Vasile Coman”",
    ],
    "University of Petrosani": [
        "Facultatea de Mine",
        "Facultatea de Inginerie Mecanică și Electrică",
        "Facultatea de Științe Economice, Administrative și Sociale",
    ],
    "University of Pitesti": [
        "Facultatea de Științe, Educație Fizică și Informatică",
        "Facultatea de Mecanică și Tehnologie",
        "Facultatea de Electronică, Comunicații și Calculatoare",
        "Facultatea de Științe Economice și Drept",
        "Facultatea de Științe ale Educației",
        "Facultatea de Teologie, Litere, Istorie, Arte",
    ],
    "University of Sibiu": [
        "Facultatea de Teologie",
        "Facultatea de Drept „Simion Bărnuțiu”",
        "Facultatea de Litere și Arte",
        "Facultatea de Științe Socio-Umane",
        "Facultatea de Inginerie",
        "Facultatea de Medicină",
        "Facultatea de Științe",
        "Facultatea de Științe Agricole, Industrie Alimentară și Protecția Mediului",
        "Facultatea de Științe Economice",
    ],
    "University of Suceava": [
        "Facultatea de Drept și Științe Administrative",
        "Facultatea de Economie, Administrație și Afaceri",
        "Facultatea de Educație Fizică și Sport",
        "Facultatea de Inginerie Alimentară",
        "Facultatea de Inginerie Electrică și Știința Calculatoarelor",
        "Facultatea de Inginerie Mecanică, Autovehicule și Robotică",
        "Facultatea de Istorie, Geografie și Științe Sociale",
        "Facultatea de Litere și Științe ale Comunicării",
        "Facultatea de Medicină și Științe Biologice",
        "Facultatea de Științe ale Educației",
        "Facultatea de Silvicultură",
    ],
    "University of Targu Jiu": [
        "Facultatea de Inginerie și Dezvoltare Durabilă",
        "Facultatea de Științe ale Educației și Management Public",
        "Facultatea de Științe Juridice",
        "Facultatea de Științe Economice",
        "Facultatea de Științe Medicale și Comportamentale",
    ],
    "Valahia University of Targoviste": [
        "Facultatea de Științe Economice",
        "Facultatea de Drept și Științe Administrative",
        "Facultatea de Inginerie Electrică, Electronică și Tehnologia Informației",
        "Facultatea de Științe și Arte",
        "Facultatea de Ingineria Mediului și Știința Alimentelor",
        "Facultatea de Ingineria Materialelor și Mecanică",
        "Facultatea de Teologie Ortodoxă și Științele Educației",
        "Facultatea de Științe Umaniste",
        "Facultatea de Științe Politice, Litere și Comunicare",
        "Facultatea de Științe și Inginerie Alexandria",
    ],
    "West University of Timisoara": [
        "Facultatea de Arte și Design",
        "Facultatea de Chimie, Biologie, Geografie",
        "Facultatea de Drept",
        "Facultatea de Economie și de Administrare a Afacerilor",
        "Facultatea de Educație Fizică și Sport",
        "Facultatea de Fizică",
        "Facultatea de Litere, Istorie și Teologie",
        "Facultatea de Matematică și Informatică",
        "Facultatea de Muzică și Teatru",
        "Facultatea de Sociologie și Psihologie",
        "Facultatea de Științe Politice, Filosofie și Științe ale Comunicării",
    ],
}

_UNIVERSITY_NAMES = [
    "1 December University of Alba Iulia",
    "Academia Tehnica Militara",
    "Academia de Studii Economice din Bucuresti",
    'Academy of Arts "George Enescu" Iasi',
    'Academy of Music "Georghe Dima" Cluj-Napoca',
    "Babes-Bolyai University of Cluj-Napoca",
    "Constantin Brancoveanu University Pitesti",
    "Emanuel University",
    'Institute of Architecture "Ion Mincu" Bucharest',
    "Maritime University Constanta",
    "National Academy for Physical Education and Sports Bucharest",
    "National School of Political and Administrative Studies Bucharest",
    "National University of Arts",
    "National University of Music",
    "National University of Theater and Film Arts",
    "North University of Baia Mare",
    "Oradea University",
    "Petru Maior University of Targu Mures",
    "Polytechnic University of Timisoara",
    "Romanian-American University",
    "Spiru Haret University",
    "Targu-Mures University of Theatre",
    "Technical University of Civil Engineering Bucharest",
    "Technical University of Cluj-Napoca",
    "Technical University of Iasi",
    "Technical University of Timisoara",
    'Universitatea de Vest "Vasile Goldiş"',
    'University "Aurel Vlaicu" Arad',
    'University "Petre Andrei" Iasi',
    'University "Titu Maiorescu"',
    'University "Transilvania" of Brasov',
    "University Lucian Blaga of Sibiu",
    "University Oil-Gas Ploiesti",
    "University Politehnica of Bucharest",
    "University of Agriculture and Veterinary Medicine Bucharest",
    "University of Agriculture and Veterinary Medicine Cluj-Napoca",
    "University of Agriculture and Veterinary Medicine Iasi",
    "University of Agriculture and Veterinary Medicine Timisoara",
    "University of Art and Design Cluj-Napoca",
    "University of Bacau",
    "University of Bucharest",
    "University of Constanta",
    "University of Constanta Medical School",
    "University of Craiova",
    "University of Galatzi",
    "University of Iasi",
    "University of Medicine and Pharmacology of Oradea",
    "University of Medicine and Pharmacy of Bucharest",
    "University of Medicine and Pharmacy of Cluj-Napoca",
    "University of Medicine and Pharmacy of Iasi",
    "University of Medicine and Pharmacy of Targu Mures",
    "University of Medicine and Pharmacy of Timisoara",
    "University of Oradea",
    "University of Petrosani",
    "University of Pitesti",
    "University of Sibiu",
    "University of Suceava",
    "University of Targu Jiu",
    "Valahia University of Targoviste",
    "West University of Timisoara",
]

_UNIVERSITY_ALIASES: dict[str, list[str]] = {
    'University "Transilvania" of Brasov': ['University "Transilvany" of Brasov'],
    "University Oil-Gas Ploiesti": ["University Oil- Gas Ploiesti"],
}

_UNIVERSITY_KEY_TO_CANONICAL: dict[str, str] = {}
for canonical in _UNIVERSITY_NAMES:
    _UNIVERSITY_KEY_TO_CANONICAL[_normalize_university_key(canonical)] = canonical
for canonical, aliases in _UNIVERSITY_ALIASES.items():
    for alias in aliases:
        _UNIVERSITY_KEY_TO_CANONICAL[_normalize_university_key(alias)] = canonical


def normalize_university_name(name: str | None) -> str | None:
    if name is None:
        return None
    trimmed = name.strip()
    if not trimmed:
        return None
    canonical = _UNIVERSITY_KEY_TO_CANONICAL.get(_normalize_university_key(trimmed))
    return canonical or trimmed


def get_university_catalog() -> list[UniversityCatalogItem]:
    items: list[UniversityCatalogItem] = []
    for name in _UNIVERSITY_NAMES:
        items.append(
            {
                "name": name,
                "city": _guess_city(name),
                "faculties": _FACULTIES_BY_UNIVERSITY.get(name, []),
                "aliases": _UNIVERSITY_ALIASES.get(name, []),
            }
        )
    return items
